name: CI/CD

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  FORCE_COLOR: 1
  SIGNING_SECRET: "xma1238904"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up environment variables
        env:
          SIGNING_SECRET: ${{ env.SIGNING_SECRET }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install --with test

      - name: Run tests
        run: poetry run pytest
